## Numpy Array Operations


In [2]:
import numpy as np

## indexing 


In [27]:
arr=np.arange(0,10)
arr[2:7]
print("With steps: ",arr[0:10:3])
print("neg index: ",arr[10::-1])

With steps:  [0 3 6 9]
neg index:  [9 8 7 6 5 4 3 2 1 0]


In [4]:
arr2=np.array([[1,2,3],[4,5,6]])

arr2[1,2]
print(arr2[1]) #rows
print(arr2[:,1]) #column

[4 5 6]
[2 5]


## Sorting 

In [25]:
arr=np.array([1,4,3,2,6,7])
print("Sroted Array:",np.sort(arr))
arr2=np.array([[1,4,3],[5,2,5]])
print("Sorted 2d:",np.sort(arr2,axis=1)) #0 for column and 1 for row

Sroted Array: [1 2 3 4 6 7]
Sorted 2d: [[1 3 4]
 [2 5 5]]


# Filtering Arrays

In [6]:
arr=np.array([1,4,3,2,6,7])
even=arr[arr%2==0]
even

array([4, 2, 6])

## Filter With Mask

In [7]:
mask=arr>5
print("Number greate than 5 :",arr[mask])


Number greate than 5 : [6 7]


#  Fancy indexing and np.where()

In [8]:
indices=[0,2,4]
where=np.where(arr>5)
print("np where: ",arr[where])

np where:  [6 7]


In [9]:
# condition_array=np.where(arr>5 ,arr*2,arr)
condition_array=np.where(arr>5 ,"true","false")


condition_array

# Equivalent :
#if(arr>5){
# arr*2
# }else{
# arr
# }

array(['false', 'false', 'false', 'false', 'true', 'true'], dtype='<U5')

# Adding and Removing data 

In [13]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
add=arr1+arr2
add

# cobine 2 array
concat=np.concatenate((arr1,arr2))
concat

array([1, 2, 3, 4, 5, 6])

## Array Compatibility

In [14]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
c=np.array([5,6,7])
print("compatibality :",arr1.shape==arr2.shape)

compatibality : True


In [18]:
original=np.array([[1,2],[3,4]])
new_row=np.array([[5,6]])
#new roww
with_new_row=np.vstack((original,new_row))
print(with_new_row)
# new column
print("-----------------")
new_col=np.array([[5],[6]])
with_new_col=np.hstack((original,new_col))
print(with_new_col)

[[1 2]
 [3 4]
 [5 6]]
-----------------
[[1 2 5]
 [3 4 6]]


## Deleting 

In [21]:
original=np.array([1,2,3,4])
dele = np.delete (original,2)
dele

array([1, 2, 4])