In [1]:
import numpy as np 

In [3]:
# creating array from list 

arr=np.array([1,2,3,4])
print("iD array:",arr)

arr2=np.array([[1,2,3],[4,5,6]])
print("2D array ")
print(arr2)

iD array: [1 2 3 4]
2D array 
[[1 2 3]
 [4 5 6]]


List Vs numpy Array 

In [6]:
list=[1,2,3,4,5]
print(list *2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [ ]:
np_array=np.array([1,2,3,4,5]) #element wise multipliccation 
print(np_array *2)

[ 2  4  6  8 10]


In [9]:
import time 
start =time.time()
list=[i*2 for i in range (10000)]
print("\n List operation time:",time.time()-start)
start=time.time()
np_array=np.arange(10000)*2
print("\n Numpy operation time :",time.time()-start)


 List operation time: 0.002001047134399414

 Numpy operation time : 0.0


## Creating array from scratch 

In [10]:
zeros=np.zeros((3,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
ones=np.ones((3,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
full=np.full((2,2),7)
full

array([[7, 7],
       [7, 7]])

In [15]:

num=np.random.random((2,3))
num

array([[0.03195749, 0.54286455, 0.23716468],
       [0.45301259, 0.79188959, 0.88812284]])

In [16]:
sequence=np.arange(0,10) #nun inclusive 
sequence

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Vector ,Matirx,Tensor

In [18]:
vecotr=np.array((1,2))
vecotr

array([1, 2])

In [21]:
matrix=np.array(([[1,2],[3,4]]))
matrix

array([[1, 2],
       [3, 4]])

In [23]:
tensor=np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) #multidimensional array 
tensor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

## Array properties

In [24]:
arr=np.array([[1,2,3,4],[3,4,5,6]])
print("Shape:",arr.shape)
print("Dimension",arr.ndim)
print("Size",arr.size)
print("DType",arr.dtype)


Shape: (2, 4)
Dimension 2
Size 8
DType int32


## Array Reshaping

In [28]:
arr=np.arange(12)
reshape=arr.reshape(3,4)
reshape

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
# flating the rehaped matrix
flattened=reshape.flatten()
flattened

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
# raveled:return view, insted of copy i.e return original array
raveled=reshape.ravel()
raveled

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
Transpose=reshape.T
Transpose

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])