In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)
arr2=np.random.rand(3,3)
print(arr2)
arr3=np.zeros((4,4))
print(arr3)

[[1 2 3]
 [4 5 6]]
[[0.60835089 0.16214245 0.68957125]
 [0.89066459 0.22906964 0.02326931]
 [0.7748372  0.89213202 0.28898005]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
np.save('arr1.npy',arr1)

In [11]:

np.load('arr1.npy')

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
import numpy as np
import matplotlib.pyplot as plt

try:
    logo = np.load('numpylogoicon.npy', allow_pickle=True)

    plt.figure(figsize=(10,6))

    # Original image
    plt.subplot(121)
    plt.imshow(logo)
    plt.axis('off')
    plt.title("NumPy Logo")

    # Inverted image
    dark_logo = 1 - logo
    plt.subplot(122)
    plt.imshow(dark_logo)
    plt.axis('off')
    plt.title("Dark Logo")

    plt.show()

except FileNotFoundError:
    print("No file found.")

UnpicklingError: Failed to interpret file 'numpylogoicon.npy' as a pickle